// article
export const GET_HOME_PAGE_ARTICLE_LIST = 'GET_HOME_PAGE_ARTICLE_LIST'
export const GET_ZXY_ARTICLE_LIST = 'GET_ZXY_ARTICLE_LIST'
export const GET_LY_ARTICLE_LIST = 'GET_LY_ARTICLE_LIST'
export const GET_ARTICLE_BY_ID = 'GET_ARTICLE_BY_ID'
export const GET_HOT_ARTICLES = 'GET_HOT_ARTICLES'
// tag
export const GET_TAG_LIST = 'GET_TAG_LIST'
